name: Deploy Auth Server

on:
  push:
    branches:
      - server-auth

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and Deploy Go App
        run: pmgo deploy --rolling
